name: CI-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deployment:

    runs-on: ubuntu-latest
    environment: demo

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
          
    - name: Build with Maven
      run: cd my-app
    - run: mvn -B package --file ./my-app/pom.xml
    
  Staging:
  
    runs-on: ubuntu-latest
    environment: demo
    needs: [Deployment]
    steps:
    - uses: actions/checkout@v3
    - name: docker task
      uses: Azure/docker-login@v1
      with:
       login-server: azuredev1000.azurecr.io
       username: azuredev1000
       password: CfCT9lSQZZH0/EiRIyFn54Vuj16B6L2FHcWrOCdjmQ+ACRD1S4uQ
    - run: |
       docker build . -t azuredev1000.azurecr.io/demo:v1
       docker push azuredev1000.azurecr.io/demo:v1
        
      
      
      
      
    
